---
- include_vars: secret.yml

- name: create redis directory
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /etc/redis
    - /var/redis

- name: create redis.conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
  notify: restart redis container
