---
- include_vars: secret.yml

- name: bind 0.0.0.0
  replace:
    dest: /etc/redis/redis.conf
    regexp: '^bind\s+127\.0\.0\.1$'
    replace: 'bind 0.0.0.0'
  notify: restart redis-server

- name: set password
  replace:
    dest: /etc/redis/redis.conf
    regexp: '^#\*requirepass\s+.+$'
    replace: 'requirepass {{ redis_password }}'
  notify: restart redis-server
