---
- name: create data directory
  file:
    path: /var/docker/influxdb
    state: directory
    recurse: yes

- name: recreate docker container
  docker_container:
    name: influxdb
    image: influxdb
    state: started
    restart_policy: always
    recreate: yes
    ports:
      - '8086:8086'
    volumes:
      - '/var/docker/influxdb:/var/lib/influxdb'
