---
- name: common
  hosts:
    - conoha
  roles:
    - common
  tags:
    - common

- name: docker
  hosts:
    - conoha
  roles:
    - docker
  tags:
    - docker

- name: kubernetes
  hosts:
    - conoha
  roles:
    - kubernetes
  tags:
    - kubernetes

# - name: dokku
#   hosts:
#     - conoha
#   roles:
#     - dokku
#   tags:
#     - dokku

# - name: redis
#   hosts:
#     - conoha
#   roles:
#     - redis
#   tags:
#     - redis

# - name: mackerel
#   hosts:
#     - conoha
#   roles:
#     - mackerel
#   tags:
#     - mackerel
