---
- name: common
  hosts:
    - conoha
    - cloudn
  roles:
    - common
  tags:
    - common

- name: docker
  hosts:
    - conoha
    - cloudn
  roles:
    - docker
  tags:
    - docker

- name: dokku
  hosts:
    - conoha
  roles:
    - dokku
  tags:
    - dokku

- name: redis
  hosts:
    - conoha
  roles:
    - redis
  tags:
    - redis

- name: mackerel
  hosts:
    - conoha
  roles:
    - mackerel
  tags:
    - mackerel

- name: hackathon
  hosts:
    - cloudn
  roles:
    - hackathon
  tags:
    - hackathon
