---
- name: install dokku
  apt:
    name: dokku

- name: install core plugins with dependencies
  command: dokku plugin:install-dependencies --core

- name: allow nginx
  ufw:
    rule: allow
    name: Nginx Full
