---
- include: prerequisites.yml
  become: yes
  tags: dokku_prerequisites

- include: install.yml
  become: yes
  tags: dokku_install

- include: plugin.yml
  become: yes
  with_items: '{{ dokku_plugins }}'
  tags: dockku_plugin

- include: nginx.yml
  become: yes
  tags: dokku_nginx
