---
- include_tasks: prerequisites.yml
  become: yes
  tags: dokku_prerequisites

- include_tasks: install.yml
  become: yes
  tags: dokku_install

- include_tasks: plugin.yml
  become: yes
  with_items: '{{ dokku_plugins }}'
  tags: dockku_plugin

- include_tasks: nginx.yml
  become: yes
  tags: dokku_nginx
