---
- include: prerequisites.yml
  become: yes
  tags: mackerel_prerequisites

- include: install.yml
  become: yes
  tags: mackerel_install

- include: config.yml
  become: yes
  tags: mackerel_config
