---
# https://gist.github.com/mattiaslundberg/ba214a35060d3c8603e9b1ec8627d349
- include_vars: secret.yml

- name: install letsencrypt
  apt:
    name: letsencrypt

- name: create letsencrypt directory
  file:
    path: /var/www/letsencrypt
    state: directory

- name: create letsencrypt certification
  shell: 'letsencrypt certonly -n -m {{ letsencrypt_email }} --agree-tos -d {{ inventory_hostname }} --webroot -w /var/www/letsencrypt'
  args:
    creates: '/etc/letsencrypt/live/{{ inventory_hostname }}'

- name: generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: add cronjob for letsencrypt certification renewal
  cron:
    name: letsencrypt certification renewal
    special_time: weekly
    job: 'letsencrypt renew && service nginx reload'

- name: create letsencrypt nginx site
  template:
    src: letsencrypt.j2
    dest: /etc/nginx/sites-enabled/letsencrypt
  notify: restart nginx

- name: create hackathon nginx site
  template:
    src: hackathon.j2
    dest: /etc/nginx/sites-enabled/hackathon
  notify: restart nginx
