---
- include_tasks: user.yml
  become: yes
  tags: hackathon_user

- include_tasks: sudo.yml
  become: yes
  tags: hackathon_sudo

- include_tasks: nginx.yml
  become: yes
  tags: hackathon_nginx

- include_tasks: letsencrypt.yml
  become: yes
  tags: hackathon_letsencrypt

- include_tasks: cleanup.yml
  become: yes
  tags: hackathon_cleanup
