---
- name: install nginx
  apt:
    name: nginx

- name: allow nginx full
  ufw:
    rule: allow
    name: Nginx Full

- name: copy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
