---
- include_vars: secret.yml
  tags: hackathon_user_change_your_password

- name: change your password
  user:
    name: '{{ ansible_env.USER }}'
    password: '{{ ubuntu_password }}'
  tags: hackathon_user_change_your_password

- name: create ninja user and add to docker group
  user:
    name: ninja
    password: '{{ ninja_password }}'
    groups: docker
    append: yes
    shell: /bin/bash
