---
- name: copy source.list
  template:
    src: source.list.j2
    dest: /etc/apt/sources.list

- name: update all packages
  apt: update_cache=yes upgrade=dist
  register: package_updated

- name: remove unused packages
  command: apt-get autoremove
  when: package_updated|changed

- name: cleanup local caches
  command: apt-get clean
  when: package_updated|changed
