---
- name: create data directory
  file:
    path: /var/docker/chronograf
    state: directory
    recurse: yes

- name: recreate chronograf container
  docker_container:
    name: chronograf
    image: chronograf
    state: started
    restart_policy: always
    recreate: yes
    ports:
      - '8888:8888'
    volumes:
      - '/var/docker/chronograf:/var/lib/chronograf'
