---
- name: install docker
  apt:
    name: docker-engine
  notify:
    - restart host
    - wait for host to come back

- name: enable docker api
  replace:
    path: /lib/systemd/system/docker.service
    regexp: 'ExecStart=/usr/bin/dockerd -H fd://$'
    replace: 'ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:{{ docker_api_port }}'
  register: enable_docker_api

- name: reload systemd manager configuration
  command: systemctl daemon-reload
  when: enable_docker_api|changed
  notify: restart docker daemon

- name: start and enable docker daemon
  service:
    name: docker
    state: started
    enabled: yes
