---
- name: install docker
  apt:
    name: docker-engine
  notify: ['restart host', 'wait for host to come back']

- name: start and enable docker daemon
  service:
    name: docker
    state: started
    enabled: yes
