---
- name: install docker community edition
  apt:
    name: docker-ce
  notify:
    - restart host
    - wait for host to come back

- name: start and enable docker daemon
  service:
    name: docker
    state: started
    enabled: yes
