---
- include: prerequisites.yml
  become: yes
  tags: docker_prerequisites

- include: install.yml
  become: yes
  tags: docker_install

- include: api.yml
  become: yes
  tags: docker_api

- include: python.yml
  become: yes
  tags: docker_python

- include: group.yml
  become: yes
  tags: docker_group
