---
- name: get kernel release
  command: uname -r
  register: get_kernel_release

- name: install required packages
  apt:
    name: '{{ item }}'
  with_items:
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-{{ get_kernel_release.stdout }}

- name: add new gpg key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'

- name: create docker.list
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  register: create_docker_list

- name: update apt package index
  apt:
    update_cache: yes
  when: create_docker_list|changed
