---
- name: create telegrafconfiguration directory
  file:
    path: /etc/docker/telegraf
    state: directory
    recurse: yes

- name: create telegraf.conf
  template:
    src: telegraf.conf.j2
    dest: /etc/docker/telegraf/telegraf.conf
